# Generated by Django 5.2.7 on 2025-10-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_delete_customer_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hello.user')),
            ],
            options={
                'db_table': 'hello_visit',
                'indexes': [models.Index(fields=['visited_at'], name='hello_visit_visited_bbf27f_idx'), models.Index(fields=['user', 'visited_at'], name='hello_visit_user_id_9224b2_idx')],
            },
        ),
    ]
