# Generated by Django 5.2.7 on 2025-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
