# Generated by Django 4.2 on 2025-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('td_username', models.CharField(max_length=150, unique=True)),
                ('excursions', models.TextField(blank=True)),
            ],
        ),
    ]
