# Generated by Django 5.2.7 on 2025-10-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
